# -*- mode: ruby -*-
# vi: set ft=ruby :

# dependent environment variables:
#   BASIC_AUTH_USER   BASIC認証ユーザー
#   BASIC_AUTH_PASS   BASIC認証パスワード
#   
#   e.g.) BASIC_AUTH_USER=foo BASIC_AUTH_PASS=bar vagrant up

$vm_ip = "192.168.5.100"
$vm_memory = 1024

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"

  # Make exam simplify
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.memory = $vm_memory
  end

  ## Port forwarding for Web app
  config.vm.network :forwarded_port, guest: 8080, host: 5001
  config.vm.network :private_network, ip: $vm_ip

  config.vm.synced_folder "./app", "/var/www/html", :type => "nfs"

  $basic_auth_arg = ""
  if ENV['BASIC_AUTH_USER'] && ENV['BASIC_AUTH_PASS']
    $basic_auth_arg = "-u #{ENV['BASIC_AUTH_USER']} -p #{ENV['BASIC_AUTH_PASS']}"
  end
  config.vm.provision :shell, path: "scripts/provision.sh"
  config.vm.provision :shell, path: "scripts/basic_auth.sh", run: 'always', args: $basic_auth_arg
  config.vm.provision :shell, path: "scripts/run.sh", run: "always"
end
