# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_memory = 1024

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Make exam simplify
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.memory = $vm_memory
  end
  
  config.vm.define "tx" do |tx|
    ## Port forwarding for Web app
    tx.vm.hostname = "tx"
    tx.vm.network :private_network, ip: "192.168.5.100"
  end
  
  config.vm.define "rx" do |rx|
    ## Port forwarding for Web app
    rx.vm.hostname = "rx"
    rx.vm.network :forwarded_port, guest: 24224, host: 24224
    rx.vm.network :forwarded_port, guest: 5601, host: 5601
    rx.vm.network :forwarded_port, guest: 9292, host: 9292
    rx.vm.network :private_network, ip: "192.168.5.110"

    rx.vm.synced_folder "./log", "/var/log/app", :type => "nfs"
  end
  
  config.vm.provision :shell, path: "scripts/provision.sh"
  config.vm.provision :shell, path: "scripts/build.sh"
  config.vm.provision :shell, path: "scripts/run.sh", run: "always"
end
